<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.klustr</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>sync-server</artifactId>

    <dependencies>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.18.1</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>consent-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>console-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>event-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>person-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>notification-api</artifactId>
            <version>0.1.0</version>
        </dependency>


        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <!-- clean dart -->
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.3.2</version>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${project.basedir}/lib</directory>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                    <followSymlinks>false</followSymlinks>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>generate-stamp-file</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>tools.DockerStamp</mainClass>
                            <classpathScope>compile</classpathScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- docker -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <to>
                        <image>registry.dev.klustr.io/klustr.io/console-api/sync-api</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                        <tags>
                            <tag>latest</tag>
                        </tags>
                    </to>
                    <from>
                        <image>registry.dev.klustr.io/klustr.io/jdk-base-21-jammy</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                    </from>
                    <container>
                        <ports>
                            <port>7777</port>
                        </ports>
                    </container>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot}</version>
                <configuration>
                    <executable>true</executable>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>