<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.klustr</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>common-models</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>4.1</version>
            <scope>test</scope>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.3.2</version>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${project.basedir}/src/main/java/io/klustr/schemas
                                    </directory>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                    <followSymlinks>false</followSymlinks>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>1.2.1</version>
                <dependencies>
                    <dependency>
                        <groupId>io.klustr</groupId>
                        <artifactId>common</artifactId>
                        <version>0.1.0</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <sourceDirectory>${basedir}/src/main/resources/schemas</sourceDirectory>
                    <outputDirectory>src/main/java</outputDirectory>
                    <targetPackage>io.klustr.schemas</targetPackage>
                    <includeAdditionalProperties>false</includeAdditionalProperties>
                    <useTitleAsClassname>true</useTitleAsClassname>
                    <generateBuilders>true</generateBuilders>
                    <useJodaDates>true</useJodaDates>
                    <includeToString>false</includeToString>
                    <includeHashcodeAndEquals>false</includeHashcodeAndEquals>

<!--                    <includeTypeInfo>true</includeTypeInfo>-->
                    <annotationStyle>jackson2</annotationStyle>
                    <customAnnotator>io.klustr.json.JsonSchemaFeatureAnnotator</customAnnotator>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>