
package io.klustr.schemas.integrations.ory;

import java.net.URI;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.annotation.processing.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.klustr.schemas.console.AccessTokenStrategy;
import io.klustr.schemas.console.SubjectType;
import io.klustr.schemas.console.TokenEndpointAuthMethod;
import org.joda.time.DateTime;


/**
 * OryClient
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "access_token_strategy",
    "subject_type",
    "token_endpoint_auth_method",
    "response_types",
    "allowed_cors_origins",
    "audience",
    "client_id",
    "client_name",
    "client_secret",
    "client_uri",
    "contacts",
    "created_at",
    "logo_uri",
    "metadata",
    "owner",
    "policy_uri",
    "redirect_uris",
    "refresh_token_grant_access_token_lifespan",
    "refresh_token_grant_id_token_lifespan",
    "refresh_token_grant_refresh_token_lifespan",
    "client_credentials_grant_access_token_lifespan",
    "request_uris",
    "grant_types",
    "scope",
    "sector_identifier_uri",
    "skip_consent",
    "tos_uri",
    "userinfo_signed_response_alg"
})
@Generated("jsonschema2pojo")
public class OryClient {

    @JsonProperty("access_token_strategy")
    private AccessTokenStrategy accessTokenStrategy;
    @JsonProperty("subject_type")
    private SubjectType subjectType;
    @JsonProperty("token_endpoint_auth_method")
    private TokenEndpointAuthMethod tokenEndpointAuthMethod;
    @JsonProperty("response_types")
    private List<Object> responseTypes = new ArrayList<Object>();
    @JsonProperty("allowed_cors_origins")
    private List<java.lang.String> allowedCorsOrigins = new ArrayList<java.lang.String>();
    @JsonProperty("audience")
    @JsonDeserialize(as = java.util.LinkedHashSet.class)
    private Set<String> audience = new LinkedHashSet<String>();
    /**
     * The ID is autogenerated and immutable.
     * (Required)
     * 
     */
    @JsonProperty("client_id")
    @JsonPropertyDescription("The ID is autogenerated and immutable.")
    private java.lang.String clientId;
    /**
     * The human-readable name of the client to be presented to the end-user during authorization.
     * (Required)
     * 
     */
    @JsonProperty("client_name")
    @JsonPropertyDescription("The human-readable name of the client to be presented to the end-user during authorization.")
    private java.lang.String clientName;
    /**
     * The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.
     * (Required)
     * 
     */
    @JsonProperty("client_secret")
    @JsonPropertyDescription("The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.")
    private java.lang.String clientSecret;
    /**
     * ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
     * (Required)
     * 
     */
    @JsonProperty("client_uri")
    @JsonPropertyDescription("ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.")
    private URI clientUri;
    @JsonProperty("contacts")
    private List<Object> contacts = new ArrayList<Object>();
    @JsonProperty("created_at")
    private DateTime createdAt;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("logo_uri")
    private URI logoUri;
    /**
     * Key value pairs for registering with the client.
     * 
     */
    @JsonProperty("metadata")
    @JsonPropertyDescription("Key value pairs for registering with the client.")
    private Metadata metadata;
    /**
     * Owner is a string identifying the owner of the OAuth 2.0 Client.
     * 
     */
    @JsonProperty("owner")
    @JsonPropertyDescription("Owner is a string identifying the owner of the OAuth 2.0 Client.")
    private java.lang.String owner;
    /**
     * PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.
     * (Required)
     * 
     */
    @JsonProperty("policy_uri")
    @JsonPropertyDescription("PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.")
    private URI policyUri;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("redirect_uris")
    private List<java.lang.String> redirectUris = new ArrayList<java.lang.String>();
    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_access_token_lifespan")
    @JsonPropertyDescription("Specify a time duration in milliseconds, seconds, minutes, hours.")
    private java.lang.String refreshTokenGrantAccessTokenLifespan;
    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_id_token_lifespan")
    @JsonPropertyDescription("Specify a time duration in milliseconds, seconds, minutes, hours.")
    private java.lang.String refreshTokenGrantIdTokenLifespan;
    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_refresh_token_lifespan")
    @JsonPropertyDescription("Specify a time duration in milliseconds, seconds, minutes, hours.")
    private java.lang.String refreshTokenGrantRefreshTokenLifespan;
    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("client_credentials_grant_access_token_lifespan")
    @JsonPropertyDescription("Specify a time duration in milliseconds, seconds, minutes, hours.")
    private java.lang.String clientCredentialsGrantAccessTokenLifespan;
    @JsonProperty("request_uris")
    private List<java.lang.String> requestUris = new ArrayList<java.lang.String>();
    @JsonProperty("grant_types")
    private List<java.lang.String> grantTypes = new ArrayList<java.lang.String>();
    /**
     * Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
     * 
     */
    @JsonProperty("scope")
    @JsonPropertyDescription("Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.")
    private java.lang.String scope;
    /**
     * URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP. The URL references a file with a single JSON array of redirect_uri values.
     * 
     */
    @JsonProperty("sector_identifier_uri")
    @JsonPropertyDescription("URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP. The URL references a file with a single JSON array of redirect_uri values.")
    private java.lang.String sectorIdentifierUri;
    /**
     * SkipConsent skips the consent screen for this client. This field can only be set from the admin API.
     * 
     */
    @JsonProperty("skip_consent")
    @JsonPropertyDescription("SkipConsent skips the consent screen for this client. This field can only be set from the admin API.")
    private Boolean skipConsent;
    /**
     * A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.
     * 
     */
    @JsonProperty("tos_uri")
    @JsonPropertyDescription("A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.")
    private URI tosUri;
    /**
     * UserInfoResponseAlgo
     * <p>
     * The algorithim to use when returning user info. Switching to RS256 will return a signed JWT token. By default this is the return.
     * 
     */
    @JsonProperty("userinfo_signed_response_alg")
    @JsonPropertyDescription("The algorithim to use when returning user info. Switching to RS256 will return a signed JWT token. By default this is the return.")
    private OryClient.UserInfoResponseAlgo userinfoSignedResponseAlg;

    @JsonProperty("access_token_strategy")
    public AccessTokenStrategy getAccessTokenStrategy() {
        return accessTokenStrategy;
    }

    @JsonProperty("access_token_strategy")
    public void setAccessTokenStrategy(AccessTokenStrategy accessTokenStrategy) {
        this.accessTokenStrategy = accessTokenStrategy;
    }

    public OryClient withAccessTokenStrategy(AccessTokenStrategy accessTokenStrategy) {
        this.accessTokenStrategy = accessTokenStrategy;
        return this;
    }

    @JsonProperty("subject_type")
    public SubjectType getSubjectType() {
        return subjectType;
    }

    @JsonProperty("subject_type")
    public void setSubjectType(SubjectType subjectType) {
        this.subjectType = subjectType;
    }

    public OryClient withSubjectType(SubjectType subjectType) {
        this.subjectType = subjectType;
        return this;
    }

    @JsonProperty("token_endpoint_auth_method")
    public TokenEndpointAuthMethod getTokenEndpointAuthMethod() {
        return tokenEndpointAuthMethod;
    }

    @JsonProperty("token_endpoint_auth_method")
    public void setTokenEndpointAuthMethod(TokenEndpointAuthMethod tokenEndpointAuthMethod) {
        this.tokenEndpointAuthMethod = tokenEndpointAuthMethod;
    }

    public OryClient withTokenEndpointAuthMethod(TokenEndpointAuthMethod tokenEndpointAuthMethod) {
        this.tokenEndpointAuthMethod = tokenEndpointAuthMethod;
        return this;
    }

    @JsonProperty("response_types")
    public List<Object> getResponseTypes() {
        return responseTypes;
    }

    @JsonProperty("response_types")
    public void setResponseTypes(List<Object> responseTypes) {
        this.responseTypes = responseTypes;
    }

    public OryClient withResponseTypes(List<Object> responseTypes) {
        this.responseTypes = responseTypes;
        return this;
    }

    @JsonProperty("allowed_cors_origins")
    public List<java.lang.String> getAllowedCorsOrigins() {
        return allowedCorsOrigins;
    }

    @JsonProperty("allowed_cors_origins")
    public void setAllowedCorsOrigins(List<java.lang.String> allowedCorsOrigins) {
        this.allowedCorsOrigins = allowedCorsOrigins;
    }

    public OryClient withAllowedCorsOrigins(List<java.lang.String> allowedCorsOrigins) {
        this.allowedCorsOrigins = allowedCorsOrigins;
        return this;
    }

    @JsonProperty("audience")
    public Set<String> getAudience() {
        return audience;
    }

    @JsonProperty("audience")
    public void setAudience(Set<String> audience) {
        this.audience = audience;
    }

    public OryClient withAudience(Set<String> audience) {
        this.audience = audience;
        return this;
    }

    /**
     * The ID is autogenerated and immutable.
     * (Required)
     * 
     */
    @JsonProperty("client_id")
    public java.lang.String getClientId() {
        return clientId;
    }

    /**
     * The ID is autogenerated and immutable.
     * (Required)
     * 
     */
    @JsonProperty("client_id")
    public void setClientId(java.lang.String clientId) {
        this.clientId = clientId;
    }

    public OryClient withClientId(java.lang.String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * The human-readable name of the client to be presented to the end-user during authorization.
     * (Required)
     * 
     */
    @JsonProperty("client_name")
    public java.lang.String getClientName() {
        return clientName;
    }

    /**
     * The human-readable name of the client to be presented to the end-user during authorization.
     * (Required)
     * 
     */
    @JsonProperty("client_name")
    public void setClientName(java.lang.String clientName) {
        this.clientName = clientName;
    }

    public OryClient withClientName(java.lang.String clientName) {
        this.clientName = clientName;
        return this;
    }

    /**
     * The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.
     * (Required)
     * 
     */
    @JsonProperty("client_secret")
    public java.lang.String getClientSecret() {
        return clientSecret;
    }

    /**
     * The secret will be included in the create request as cleartext, and then never again. The secret is kept in hashed format and is not recoverable once lost.
     * (Required)
     * 
     */
    @JsonProperty("client_secret")
    public void setClientSecret(java.lang.String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public OryClient withClientSecret(java.lang.String clientSecret) {
        this.clientSecret = clientSecret;
        return this;
    }

    /**
     * ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
     * (Required)
     * 
     */
    @JsonProperty("client_uri")
    public URI getClientUri() {
        return clientUri;
    }

    /**
     * ClientURI is a URL string of a web page providing information about the client. If present, the server SHOULD display this URL to the end-user in a clickable fashion.
     * (Required)
     * 
     */
    @JsonProperty("client_uri")
    public void setClientUri(URI clientUri) {
        this.clientUri = clientUri;
    }

    public OryClient withClientUri(URI clientUri) {
        this.clientUri = clientUri;
        return this;
    }

    @JsonProperty("contacts")
    public List<Object> getContacts() {
        return contacts;
    }

    @JsonProperty("contacts")
    public void setContacts(List<Object> contacts) {
        this.contacts = contacts;
    }

    public OryClient withContacts(List<Object> contacts) {
        this.contacts = contacts;
        return this;
    }

    @JsonProperty("created_at")
    public DateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("created_at")
    public void setCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OryClient withCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("logo_uri")
    public URI getLogoUri() {
        return logoUri;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("logo_uri")
    public void setLogoUri(URI logoUri) {
        this.logoUri = logoUri;
    }

    public OryClient withLogoUri(URI logoUri) {
        this.logoUri = logoUri;
        return this;
    }

    /**
     * Key value pairs for registering with the client.
     * 
     */
    @JsonProperty("metadata")
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Key value pairs for registering with the client.
     * 
     */
    @JsonProperty("metadata")
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    public OryClient withMetadata(Metadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Owner is a string identifying the owner of the OAuth 2.0 Client.
     * 
     */
    @JsonProperty("owner")
    public java.lang.String getOwner() {
        return owner;
    }

    /**
     * Owner is a string identifying the owner of the OAuth 2.0 Client.
     * 
     */
    @JsonProperty("owner")
    public void setOwner(java.lang.String owner) {
        this.owner = owner;
    }

    public OryClient withOwner(java.lang.String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.
     * (Required)
     * 
     */
    @JsonProperty("policy_uri")
    public URI getPolicyUri() {
        return policyUri;
    }

    /**
     * PolicyURI is a URL string that points to a human-readable privacy policy document that describes how the deployment organization collects, uses, retains, and discloses personal data.
     * (Required)
     * 
     */
    @JsonProperty("policy_uri")
    public void setPolicyUri(URI policyUri) {
        this.policyUri = policyUri;
    }

    public OryClient withPolicyUri(URI policyUri) {
        this.policyUri = policyUri;
        return this;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("redirect_uris")
    public List<java.lang.String> getRedirectUris() {
        return redirectUris;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("redirect_uris")
    public void setRedirectUris(List<java.lang.String> redirectUris) {
        this.redirectUris = redirectUris;
    }

    public OryClient withRedirectUris(List<java.lang.String> redirectUris) {
        this.redirectUris = redirectUris;
        return this;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_access_token_lifespan")
    public java.lang.String getRefreshTokenGrantAccessTokenLifespan() {
        return refreshTokenGrantAccessTokenLifespan;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_access_token_lifespan")
    public void setRefreshTokenGrantAccessTokenLifespan(java.lang.String refreshTokenGrantAccessTokenLifespan) {
        this.refreshTokenGrantAccessTokenLifespan = refreshTokenGrantAccessTokenLifespan;
    }

    public OryClient withRefreshTokenGrantAccessTokenLifespan(java.lang.String refreshTokenGrantAccessTokenLifespan) {
        this.refreshTokenGrantAccessTokenLifespan = refreshTokenGrantAccessTokenLifespan;
        return this;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_id_token_lifespan")
    public java.lang.String getRefreshTokenGrantIdTokenLifespan() {
        return refreshTokenGrantIdTokenLifespan;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_id_token_lifespan")
    public void setRefreshTokenGrantIdTokenLifespan(java.lang.String refreshTokenGrantIdTokenLifespan) {
        this.refreshTokenGrantIdTokenLifespan = refreshTokenGrantIdTokenLifespan;
    }

    public OryClient withRefreshTokenGrantIdTokenLifespan(java.lang.String refreshTokenGrantIdTokenLifespan) {
        this.refreshTokenGrantIdTokenLifespan = refreshTokenGrantIdTokenLifespan;
        return this;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_refresh_token_lifespan")
    public java.lang.String getRefreshTokenGrantRefreshTokenLifespan() {
        return refreshTokenGrantRefreshTokenLifespan;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("refresh_token_grant_refresh_token_lifespan")
    public void setRefreshTokenGrantRefreshTokenLifespan(java.lang.String refreshTokenGrantRefreshTokenLifespan) {
        this.refreshTokenGrantRefreshTokenLifespan = refreshTokenGrantRefreshTokenLifespan;
    }

    public OryClient withRefreshTokenGrantRefreshTokenLifespan(java.lang.String refreshTokenGrantRefreshTokenLifespan) {
        this.refreshTokenGrantRefreshTokenLifespan = refreshTokenGrantRefreshTokenLifespan;
        return this;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("client_credentials_grant_access_token_lifespan")
    public java.lang.String getClientCredentialsGrantAccessTokenLifespan() {
        return clientCredentialsGrantAccessTokenLifespan;
    }

    /**
     * Specify a time duration in milliseconds, seconds, minutes, hours.
     * 
     */
    @JsonProperty("client_credentials_grant_access_token_lifespan")
    public void setClientCredentialsGrantAccessTokenLifespan(java.lang.String clientCredentialsGrantAccessTokenLifespan) {
        this.clientCredentialsGrantAccessTokenLifespan = clientCredentialsGrantAccessTokenLifespan;
    }

    public OryClient withClientCredentialsGrantAccessTokenLifespan(java.lang.String clientCredentialsGrantAccessTokenLifespan) {
        this.clientCredentialsGrantAccessTokenLifespan = clientCredentialsGrantAccessTokenLifespan;
        return this;
    }

    @JsonProperty("request_uris")
    public List<java.lang.String> getRequestUris() {
        return requestUris;
    }

    @JsonProperty("request_uris")
    public void setRequestUris(List<java.lang.String> requestUris) {
        this.requestUris = requestUris;
    }

    public OryClient withRequestUris(List<java.lang.String> requestUris) {
        this.requestUris = requestUris;
        return this;
    }

    @JsonProperty("grant_types")
    public List<java.lang.String> getGrantTypes() {
        return grantTypes;
    }

    @JsonProperty("grant_types")
    public void setGrantTypes(List<java.lang.String> grantTypes) {
        this.grantTypes = grantTypes;
    }

    public OryClient withGrantTypes(List<java.lang.String> grantTypes) {
        this.grantTypes = grantTypes;
        return this;
    }

    /**
     * Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
     * 
     */
    @JsonProperty("scope")
    public java.lang.String getScope() {
        return scope;
    }

    /**
     * Scope is a string containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.
     * 
     */
    @JsonProperty("scope")
    public void setScope(java.lang.String scope) {
        this.scope = scope;
    }

    public OryClient withScope(java.lang.String scope) {
        this.scope = scope;
        return this;
    }

    /**
     * URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP. The URL references a file with a single JSON array of redirect_uri values.
     * 
     */
    @JsonProperty("sector_identifier_uri")
    public java.lang.String getSectorIdentifierUri() {
        return sectorIdentifierUri;
    }

    /**
     * URL using the https scheme to be used in calculating Pseudonymous Identifiers by the OP. The URL references a file with a single JSON array of redirect_uri values.
     * 
     */
    @JsonProperty("sector_identifier_uri")
    public void setSectorIdentifierUri(java.lang.String sectorIdentifierUri) {
        this.sectorIdentifierUri = sectorIdentifierUri;
    }

    public OryClient withSectorIdentifierUri(java.lang.String sectorIdentifierUri) {
        this.sectorIdentifierUri = sectorIdentifierUri;
        return this;
    }

    /**
     * SkipConsent skips the consent screen for this client. This field can only be set from the admin API.
     * 
     */
    @JsonProperty("skip_consent")
    public Boolean getSkipConsent() {
        return skipConsent;
    }

    /**
     * SkipConsent skips the consent screen for this client. This field can only be set from the admin API.
     * 
     */
    @JsonProperty("skip_consent")
    public void setSkipConsent(Boolean skipConsent) {
        this.skipConsent = skipConsent;
    }

    public OryClient withSkipConsent(Boolean skipConsent) {
        this.skipConsent = skipConsent;
        return this;
    }

    /**
     * A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.
     * 
     */
    @JsonProperty("tos_uri")
    public URI getTosUri() {
        return tosUri;
    }

    /**
     * A URL string pointing to a human-readable terms of service document for the client that describes a contractual relationship between the end-user and the client that the end-user accepts when authorizing the client.
     * 
     */
    @JsonProperty("tos_uri")
    public void setTosUri(URI tosUri) {
        this.tosUri = tosUri;
    }

    public OryClient withTosUri(URI tosUri) {
        this.tosUri = tosUri;
        return this;
    }

    /**
     * UserInfoResponseAlgo
     * <p>
     * The algorithim to use when returning user info. Switching to RS256 will return a signed JWT token. By default this is the return.
     * 
     */
    @JsonProperty("userinfo_signed_response_alg")
    public OryClient.UserInfoResponseAlgo getUserinfoSignedResponseAlg() {
        return userinfoSignedResponseAlg;
    }

    /**
     * UserInfoResponseAlgo
     * <p>
     * The algorithim to use when returning user info. Switching to RS256 will return a signed JWT token. By default this is the return.
     * 
     */
    @JsonProperty("userinfo_signed_response_alg")
    public void setUserinfoSignedResponseAlg(OryClient.UserInfoResponseAlgo userinfoSignedResponseAlg) {
        this.userinfoSignedResponseAlg = userinfoSignedResponseAlg;
    }

    public OryClient withUserinfoSignedResponseAlg(OryClient.UserInfoResponseAlgo userinfoSignedResponseAlg) {
        this.userinfoSignedResponseAlg = userinfoSignedResponseAlg;
        return this;
    }


    /**
     * UserInfoResponseAlgo
     * <p>
     * The algorithim to use when returning user info. Switching to RS256 will return a signed JWT token. By default this is the return.
     * 
     */
    @Generated("jsonschema2pojo")
    public enum UserInfoResponseAlgo {

        RS_256("RS256"),
        NONE("none");
        private final java.lang.String value;
        private final static Map<java.lang.String, OryClient.UserInfoResponseAlgo> CONSTANTS = new HashMap<java.lang.String, OryClient.UserInfoResponseAlgo>();

        static {
            for (OryClient.UserInfoResponseAlgo c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        UserInfoResponseAlgo(java.lang.String value) {
            this.value = value;
        }

        @Override
        public java.lang.String toString() {
            return this.value;
        }

        @JsonValue
        public java.lang.String value() {
            return this.value;
        }

        @JsonCreator
        public static OryClient.UserInfoResponseAlgo fromValue(java.lang.String value) {
            OryClient.UserInfoResponseAlgo constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

}
