version: "3.8"

services:
  ${PROJECT}:
    image: registry.dev.klustr.io/klustr.io/developer-machine/main:latest
    container_name: ${PROJECT}
    restart: always
    ports:
      - "${EXPOSE_PORT}:22"
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
        reservations:
          cpus: "${CPU_RESERVE}"
          memory: "${MEMORY_RESERVE}"
    environment:
      ORG_ID: ${ORG}
      PROJECT_ID: ${PROJECT}
      MACHINE_TYPE: ${MACHINE_TYPE}
      API_URL: "https://api.dev.klustr.io"
      PERSISTENT_VOLUME_ID: ${PERSISTENT_VOLUME_ID}
      ROOT_SERVER_URL: ${ROOT_SERVER_URL}
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      BABEL_DISABLE_CACHE: 1
    labels:
      namespace: "${PROJECT}"
      org_id: "${ORG}"
      project: "${PROJECT}"
      project_id: "${PROJECT}"
      type: "TENANT"
      machine_type: "${MACHINE_TYPE}"
      workload: "devmachine"
    networks:
      - ingress
      - ${ORG}
    dns:
      - ${DNS_HOST}
    volumes:
      - dev_data:/code

volumes:
  dev_data:
    name: "${ORG}_${PROJECT}_devmachine"

networks:
  ingress:
    external: true
  ${ORG}:
    external: true
