<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.klustr</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>server</artifactId>

    <dependencies>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>2.18.1</version>
        </dependency>

        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>2.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.angus</groupId>
            <artifactId>angus-mail</artifactId>
            <version>2.0.4</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.angus</groupId>
            <artifactId>angus-activation</artifactId>
            <version>2.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <version>${spring.boot}</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>consent-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>console-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>event-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>person-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>notification-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>document-api</artifactId>
            <version>0.1.0</version>
        </dependency>


        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>consent-openapi</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/consent</apiDocsUrl>
                            <outputFileName>consent-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>directory-openapi</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/directory</apiDocsUrl>
                            <outputFileName>directory-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>agreements-openapi</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/agreements</apiDocsUrl>
                            <outputFileName>agreements-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>identity-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/identity</apiDocsUrl>
                            <outputFileName>identity-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>projects-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/projects</apiDocsUrl>
                            <outputFileName>projects-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>catalog-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/api-catalog</apiDocsUrl>
                            <outputFileName>catalog-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ekyc-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/ekyc</apiDocsUrl>
                            <outputFileName>ekyc-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>events-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/events</apiDocsUrl>
                            <outputFileName>events-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>prompt-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7777/v3/api-docs/prompt</apiDocsUrl>
                            <outputFileName>prompt-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- docs -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <id>generate-stamp-file</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>tools.DockerStamp</mainClass>
                            <classpathScope>compile</classpathScope>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-agreements</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>single</argument>
                                <argument>${project.basedir}/src/main/api/agreements-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/agreements-api.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-agreements-domain</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>objects</argument>
                                <argument>${project.basedir}/src/main/api/agreements-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/agreements-domain.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-consent</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>single</argument>
                                <argument>${project.basedir}/src/main/api/consent-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/consent-api.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-identity</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>single</argument>
                                <argument>${project.basedir}/src/main/api/identity-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/identity-api.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-directory</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>single</argument>
                                <argument>${project.basedir}/src/main/api/directory-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/directory-api.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>run-openapi-to-plantuml-projects</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>java</executable>
                            <arguments>
                                <argument>-jar</argument>
                                <argument>openapi-to-plantuml.jar</argument>
                                <argument>single</argument>
                                <argument>${project.basedir}/src/main/api/projects-api.json</argument>
                                <argument>SVG</argument>
                                <argument>docs/projects-api.svg</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- clean dart -->
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.3.2</version>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${project.basedir}/lib</directory>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                    <followSymlinks>false</followSymlinks>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- docker -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <to>
                        <image>registry.dev.klustr.io/klustr.io/console-api/console-api</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                        <tags>
                            <tag>latest</tag>
                        </tags>
                    </to>
                    <from>
                        <image>registry.dev.klustr.io/klustr.io/jdk-base-21-jammy</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                    </from>
                    <container>
                        <ports>
                            <port>7777</port>
                        </ports>
                    </container>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot}</version>
                <configuration>
                    <executable>true</executable>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>