<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.klustr</groupId>
        <artifactId>parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>auth</artifactId>

    <dependencies>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>common-api</artifactId>
            <version>0.1.0</version>
        </dependency>


        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>consent-api</artifactId>
            <version>0.1.0</version>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>io.klustr</groupId>-->
<!--            <artifactId>console-api</artifactId>-->
<!--            <version>0.1.0</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>io.klustr</groupId>
            <artifactId>person-api</artifactId>
            <version>0.1.0</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>2.0.9</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <version>${spring.boot}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-to-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>prompt-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiDocsUrl>http://localhost:7878/v3/api-docs/prompt</apiDocsUrl>
                            <outputFileName>prompt-api.json</outputFileName>
                            <outputDir>${project.basedir}/src/main/api</outputDir>
                            <skip>false</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- clean dart
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.3.2</version>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${project.basedir}/lib</directory>
                                    <includes>
                                        <include>**</include>
                                    </includes>
                                    <followSymlinks>false</followSymlinks>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>-->
            <!-- dart generation
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.4.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.bluetrainsoftware.maven</groupId>
                        <artifactId>openapi-dart-generator</artifactId>
                        <version>7.2</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>prompt-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <output>${project.basedir}/lib/prompts</output>
                            <inputSpec>${project.basedir}/src/main/api/prompt-api.json</inputSpec>
                            <generatorName>dart2-api</generatorName>
                            <enablePostProcessFile>true</enablePostProcessFile>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <nullable>true</nullable>
                            </configOptions>
                            <additionalProperties>
                                <additionalProperty>
                                    pubName=prompt_api
                                </additionalProperty>
                                <additionalProperty>
                                    useDio5=true
                                </additionalProperty>
                            </additionalProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.4.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.bluetrainsoftware.maven</groupId>
                        <artifactId>openapi-dart-generator</artifactId>
                        <version>7.2</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>consent-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <output>${project.basedir}/lib/consent</output>
                            <inputSpec>${project.basedir}/src/main/api/consent-api.json</inputSpec>
                            <generatorName>dart2-api</generatorName>
                            <enablePostProcessFile>true</enablePostProcessFile>
                            <skipValidateSpec>true</skipValidateSpec>
                            <additionalProperties>
                                <additionalProperty>
                                    pubName=consent_api
                                </additionalProperty>
                                <additionalProperty>
                                    useDio5=true
                                </additionalProperty>
                            </additionalProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>-->

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>generate-stamp-file</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>tools.DockerStamp</mainClass>
                            <classpathScope>compile</classpathScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- docker -->
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <to>
                        <image>registry.dev.klustr.io/klustr.io/console-api/auth-api</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                        <tags>
                            <tag>latest</tag>
                        </tags>
                    </to>
                    <from>
                        <image>registry.dev.klustr.io/klustr.io/jdk-base-21-jammy</image>
                        <auth>
                            <username>${env.CI_REGISTRY_USER}</username>
                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                        </auth>
                    </from>
                    <container>
                        <ports>
                            <port>7878</port>
                        </ports>
                    </container>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot}</version>
                <configuration>
                    <executable>true</executable>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>